direction : right
title: 2023/01/30 월요일 {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

a010 : 8시00분 기상
a020 : 10시 3분 KTX 부산
a030 : 12시15분 KTX 광명

a010 -> a020 -> a030