direction: right
20230212: {
  label: 2023/02/12 일요일
  shape: text
  a010: 8시15분 기상
  a020: 집
  a030: 집
  a040: 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030
  a040 -> a050 -> a060

  구구단2
  플러터설정
  음성인식으로 영어교정하는 프로그램
}

20230211: {
  label: 2023/02/11 토요일
  shape: text
  a010: 8시00분 기상
  a020: 집
  a030: 집
  a040: 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030
  a040 -> a050 -> a060

  구구단2
  코플라이트 설치
}
20230210: {
  label: 2023/02/10 금요일
  shape: text
  a010: 8시15분 기상
  a020: 집
  a030: 집
  a040: 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030
  a040 -> a050 -> a060

  구구단2
  코플라이트 설치
  vscode 포터블
  exp11: |code
    PS C:\PycharmProjects> git config --global user.email "changhyun46@gmail.com"
    PS C:\PycharmProjects> git config --global user.name "changhyun46"

    // git 초기화
    git init

    4. repository 연결
    git remote add origin username@bitbucket.org/myname/myproject.git
    연결된 repo 확인 (fetch / push 주소 확인)

    git remote -v

    // 브랜치 뭐뭐 있는 지 확인
    git branch
    // 브랜치를 main 으로 변경
    git branch main
    git checkout main
    git branch -d master
    
    5. 새 repository에서 내용을 pull 받음으로써 git history를 동기화
    git pull origin main
    
    6. 새 repository에 파일을 업로드 하기 위해 스테이지에 파일 올림
    git add .
    git add . 은 모든 파일을 스테이지에 올린다는 뜻 
    
    7. 최초 커밋
    git commit -m "first commit"
    
    8. repository에 파일 업로드
    git push -u origin main
  |
}

20230209: {
  label: 2023/02/09 목요일
  shape: text
  a010: 8시00분 기상
  a020: 집
  a030: 2시00 도서관
  a040: 6시30 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030
  a040 -> a050 -> a060

  구구단
  별빛 도서관 -> 자전거
}

20230208: {
  label: 2023/02/08 수요일
  shape: text
  a010: 8시00분 기상
  a020: 집
  a030: 11시00 도서관
  a040: 5시30 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030
  a040 -> a050 -> a060

  구구단
  아나빠나사띠: {들숨날숨 집중}
}

20230207: {
  label: 2023/02/07 화요일
  shape: text
  a010: 7시00분 기상
  a020: 집
  a030: 집
  a040: 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030
  a040 -> a050 -> a060

  음성인식 튜터 만들기

  불안
  불안 -- 회사
  불안 -- 나
  회사: {
    |md
      일이 많고
      처리할수 없고
      확인이 어렵고
      개발자 컨트롤해야하고
      보고 해야하고
      고객에게 예스해야하고
    |
    |md
      일을 줄인다
      처리능력을 키운다
      확인능력을 키운다
      직원관리능력을 키운다
      보고능력을 키운다
      고객관리 능력은 키운다
      또는 그만둔다
    |
  }
  나: {
    |md
      몸이 아파서
      정신이 피폐해서
      쉬고 싶어서
      가슴아파서
      다른거 하고 싶어서
      더 대우 받고 싶어서
      편안거 하고 싶어서
      주체적으로 살고 싶어서
    |
    |md
      몸을 회복한다
      정신을 회복한다
      쉰다
      가슴안아프게 한다
      다른거 한다
      덜 대우 받더라도 안정적인거 
      편안한거 한다
    |
  }
  고엔카 탈락
  레일웨이 엠파이어
  꿈
  목표
  꿈 -- 편안
  꿈 -- 도서관
  꿈 -- 탐구
  꿈 -- 자동
  목표 -- 명상
  목표 -- 아나빠나사띠
  영어 ai 튜터 스픽
  p1: 인간의 힘
  P1: {
    주먹
    돈
    권력
    가문
    지혜
  }
}

20230206: {
  label: 2023/02/06 월요일
  shape: text
  a010: 7시50분 기상
  a020: 집
  a030: 12시 도서관
  a040: 5시30분 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030
  a040 -> a050 -> a060
}
