direction : right
title: 2023/01/31 화요일 {
    near: top-center
    shape: text
    style: {
      font-size: 29
      bold: true
      underline: true
    }
  }
a010 : 8시00분 기상
a020 : 도서관
a030 : 집

a010 -> a020 -> a030
플러터
아나빠나사띠
게임