direction: right
title: 2023/01/29 일요일 {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}
a010: 6시20분 기상
a020: 8시17분 KTX 광명
a030: 10시45분 KTX 부산

a010 -> a020 -> a030

엄마
점심: {
  direction: right
  회
  불고기
  오징어
}
엄마 -- 점심
온천천: {
  2시간넘게 걷기
}
엄마이야기: {
  유진이  대구 상탄거 시댁 하소연
  지원이 콩밥 거부 흰밥
  성민엄마 2시간
}
엄마 -- 온천천 -- 엄마이야기
형님
순대집: {
  direction: right
  소주: {
    shape: image
    icon: https://www.shutterstock.com/image-vector/fresh-korean-soju-drink-flat-600w-2143896949.jpg
  }
  수육
  순대
}
형님이야기: {
  3000 대출
  AI
  은퇴준비
}
형님 -- 순대집 -- 형님이야기
