direction: right

20230205: {
  label: 2023/02/05 일요일
  shape: text
  a010: 7시00분 기상
  a020: 집
  a030: 11시30분 트레이더스
  a040: 2시 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030 -> a040 -> a050 -> a060
  KFT 자동 스트리퍼 -> 알리
  개발언어 만들기
}

20230204: {
  label: 2023/02/04 토요일
  shape: text
  a010: 9시00분 기상
  a020: 집
  a030: 12시 도서관
  a040: 5시 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030 -> a040 -> a050 -> a060

  담마코리아 10일 고엔카
  ex2: |code
    상세 정보
    한국의 위빳사나 명상 코스 - 담마코리아 
    담마코리아 위빳사나 명상센터
    전라북도 진안군 마령면 덕천리 520-5
    전화(한국어): [82](10)5855-9779
    이메일: info@korea.dhamma.org
    홈페이지: http://korea.dhamma.org
    02/08 - 02/19	10일 코스
  |
  d1: 담마가는길
  d1 -> ktx 전주역 2시간 -> 마령,탑사 버스 50분 -> 덕천리 삼거리 걷기 -> 센터
  b1: 불안의 이유
  b1 -> 능력주의
  b1 -> 성공못함 -> 내책임
  b2: 알고리즘
  b3: 매카니즘
  b2: {
    보상 -> 습관 -> 일상
    일상 -> 보상
  }
  b3: {
    선택
  }

  마인드풀니스: {
    욕정은 뇌를 망친다
    분노의 바닥 -- 공포
    욕망의 바닥 -- 권태
    바른생계 -- 무엇을 하느냐가 아니라 어떻게 하느냐
  }
}

20230203: {
  label: 2023/02/03 금요일
  shape: text
  a010: 8시00분 기상
  a020: 집
  a030: 3시 자전거
  a040: 4시 목동
  a050: 5시 개봉 한신포차
  a060: 집

  a010 -> a020 -> a030 -> a040 -> a050 -> a060

  b01: 법인카드 보내기
  b02: |code
    07217 서울특별시 영등포구 당산로 41길 11, 당산 SKV1 센터 E동 5층
    ㈜엠로 문혜진 선임
  |
  b01 -- b02
  임요한
  스타: {
    최고
    최고 -> 은퇴 -> 지도자
    지도자 적성 안맞음: {
      선수보호
      스타일 다름
    }
  }
  포커

  임요한 -> 스타 -> 포커
}

20230202: 2023/02/02 목요일 {
  shape: text
  a010: 8시00분 기상
  a020: 집 4시
  a030: 홍대 오뎅집 5시
  a040: 신촌 한신포차 7시
  a050: 집 9시30분
  a060: 집

  a010 -> a020 -> a030 -> a040 -> a050 -> a060

  혀니
  hyuny
  무상
  괴로움
  무아
  무상 -> 괴로움 -> 무아: 진리
  원인
  결과
  원인 -> 결과
}

explanation: |code
  안녕하세요 정창현입니다.
  Dear all,
  Kind regards
  수고하세요~
  감사합니다.
  
  I am very happy that I was able to successfully complete the Glovis U.S. expansion project.
  In particular, Lee Seung-hun and Assistant Manager Lim Jun-hyung organized the necessary parts in a simple way,
  It seems to be a good system to use.
  And thank you to everyone who participated in the project together.
  Have a happy and relaxing day
  Have a good year this year too!
|

20230201: 2023/02/01 수요일 {
  shape: text

  a010: 9시00분 기상
  a020: 도서관
  a030: 집
  a040: 집
  a050: 집
  a060: 집

  a010 -> a020 -> a030 -> a040 -> a050 -> a060

  아나빠나사띠
  위빠사나
  메모글쓰기
}
