# d2 fmt MyD2.d2
x: {
  style: {
    stroke: "#53C0D8"
    stroke-width: 5
    shadow: true
  }
}

y: {
  style: {
    opacity: 0.6
    fill: red
    3d: true
    stroke: black
  }
}

x -> y: {
  style: {
    stroke: green
    opacity: 0.5
    stroke-width: 2
    stroke-dash: 5
  }
}
direction: right
x <- y -> z: onwards!
costumes: {
  shape: sql_table
  id: int {constraint: primary_key}
  silliness: int
  monster: int
  last_updated: timestamp
}

monsters: {
  shape: sql_table
  id: int {constraint: primary_key}
  movie: string
  weight: int
  last_updated: timestamp
}

costumes.monster -> monsters.id
explanation: |md
  # I can do headers

  - lists
  - lists

  And other normal markdown stuff
|
aws: {
  server
  jeus
}
server
aws.server -> server: 세션 카피
x1: I'm a Mac {
  link: https://apple.com
}
y1: And I'm a PC {
  link: https://microsoft.com
}
x1 <- y1: gazoontite
x1 -- y1: test

