direction: right
모모타로
모모타로.shape: oval
가족: {
    direction: right
    할아버지
    할머니
}
친구: {
    direction: right
    개
    꿩
    원숭이
}
모모타로 -- 가족
모모타로 -- 친구


가족 -- 할아버지
가족 -- 할머니

친구 -- 개
친구 -- 꿩
친구 -- 원숭이

가족.할아버지 ->  개 : 밥
가족.할머니 ->  친구.개 : 밥